t1=input("Enter Elemwnt No.1  : ")
t2=input("Enter Elemwnt No.2  : ")
t3=input("Enter Elemwnt No.3  : ")
t4=input("Enter Elemwnt No.4  : ")
t5=input("Enter Elemwnt No.5  : ")
t6=input("Enter Elemwnt No.6  : ")
t7=input("Enter Elemwnt No.7  : ")
t8=input("Enter Elemwnt No.8  : ")
t9=input("Enter Elemwnt No.9  : ")
t10=input("Enter Elemwnt No.10 : ")
t11=input("Enter Elemwnt No.11 : ")
t12=input("Enter Elemwnt No.12 : ")
t13=input("Enter Elemwnt No.13 : ")
T=(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13)
print(T.count(0))
